# To aid in running tests locally. NOT for using elasicdump as a Docker container
version: '2.1'
services:
  elasticsearch:
    ports:
      - "9200:9200"
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.3.0'
    environment:
      http.host: '0.0.0.0'
      transport.host: '127.0.0.1'
      xpack.security.enabled: 'false' # ES5 ships with security on by default which isn't configured in unit tests 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 2s
      timeout: 2s
      retries: 5
