name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        es-version: [1.5.0,2.3.4,5.6.4,6.0.0,7.0.0]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Run build script
        run: ./.github/scripts/build.sh "${{ matrix.es-version }}"
        shell: bash